# permissions for end users to edit ipcidrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubipam
    app.kubernetes.io/managed-by: kustomize
  name: ipcidr-editor-role
rules:
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipcidrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipcidrs/status
  verbs:
  - get
