# permissions for end users to view ipclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubipam
    app.kubernetes.io/managed-by: kustomize
  name: ipclaim-viewer-role
rules:
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipclaims/status
  verbs:
  - get
