---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipcidrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipcidrs/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipcidrs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipclaims/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.didactiklabs.io
  resources:
  - ipclaims/status
  verbs:
  - get
  - patch
  - update
