name: Unit tests
# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.22'
      # This step is needed as the following one tries to remove
      # kustomize for each test but has no permission to do so
      - name: Remove pre-installed kustomize
        run: sudo rm -f /usr/local/bin/kustomize
      - name: Perform the test
        run: make test
